### ISSUE TITLE
AttributeError: module 'plantcv.plantcv' has no attribute 'visualize'

### ISSUE THREAD

**Issue by AdamDimech** [danforthcenter/plantcv#391]
I have been running PlantCV workflows over a [flat directory of images](https://plantcv.readthedocs.io/en/latest/pipeline_parallel/#running-plantcv-workflows-over-a-flat-directory-of-images). I recently upgraded PlantCV to Version 3.4.0 and am now experiencing an error with pcv.visualize.pseudocolor.

I have reviewed the latest [VIS tutorial](https://plantcv.readthedocs.io/en/latest/vis_tutorial/) code (and made [necessary modifications](https://plantcv.readthedocs.io/en/latest/updating/#updating-to-v3) to [my code](https://gist.github.com/AdamDimech/e54fe95f7face972192fbd76fa83bf9a)) and get the following error:

`Traceback (most recent call last):
  File "C:/Path/To/plantcv_pipeline.py", line 142, in <module>
    main()
  File "C:/Path/To/plantcv_pipeline.py", line 133, in main
    pseudocolored_img = pcv.visualize.pseudocolor(gray_img=s, obj=None, mask=mask, axes=True, colorbar=True, cmap='jet')
AttributeError: module 'plantcv.plantcv' has no attribute 'visualize'`

I cannot figure out what I am doing wrong here. Can you help?

**Comment by HaleySchuhl** [comment]
Hi @AdamDimech ,

Thank you for providing your full python script and error messages! I haven't been able to replicate your error (I am working with PlantCV v3.4.0+3 but the `visualize` hasn't been modified since April 12th). Can you activate your PlantCV environment and then run `pip freeze` in the command line and post the output here?

**Comment by AdamDimech** [comment]
`pip freeze` Output as requested:

`attrs==18.2.0
backcall==0.1.0
bleach==3.1.0
certifi==2018.11.29
cloudpickle==0.6.1
colorama==0.4.1
cycler==0.10.0
cytoolz==0.9.0.1
dask==1.1.0
decorator==4.3.0
descartes==1.1.0
entrypoints==0.3
imageio==2.4.1
ipykernel==5.1.0
ipython==7.2.0
ipython-genutils==0.2.0
jedi==0.13.2
Jinja2==2.10
jsonschema==3.0.0a3
jupyter-client==5.2.4
jupyter-core==4.4.0
jupyterlab==0.35.3
jupyterlab-server==0.2.0
kiwisolver==1.0.1
MarkupSafe==1.1.0
matplotlib==3.0.2
mistune==0.8.4
mizani==0.5.3
mkl-fft==1.0.10
mkl-random==1.0.2
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.2
notebook==5.7.4
numpy==1.15.4
olefile==0.46
opencv-python==3.4.5.20
palettable==3.1.1
pandas==0.23.4
pandocfilters==1.4.2
parso==0.3.1
patsy==0.5.1
pickleshare==0.7.5
Pillow==5.4.1
plantcv==3.0.5
plotnine==0.5.1
prometheus-client==0.5.0
prompt-toolkit==2.0.7
Pygments==2.3.1
pyparsing==2.3.1
PyQt5==5.11.3
PyQt5-sip==4.19.13
pyrsistent==0.14.9
python-dateutil==2.7.5
pytz==2018.9
PyWavelets==1.0.1
pywinpty==0.5.5
pyzmq==17.1.2
QtPy==1.6.0
scikit-image==0.14.2
scipy==1.1.0
Send2Trash==1.5.0
six==1.12.0
statsmodels==0.9.0
terminado==0.8.1
testpath==0.4.2
toolz==0.9.0
tornado==5.1.1
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
wincertstore==0.2`

**Comment by HaleySchuhl** [comment]
Thanks @AdamDimech ,

It looks like your environment has PlantCV v3.0.5 which was released before the visualize sub-package was created. Originally the function `pcv.pseudocolor` was added in v3.1 and then the visualize sub-package was added in v3.2. [Updating PlantCV](https://plantcv.readthedocs.io/en/latest/updating/) ought to resolve the attribute error. Sometimes I have remove my environment for some reason to get it to update. Please let us know if you need any help with updating!

**Comment by AdamDimech** [comment]
I updated Conda/Anaconda, updated my plantcv environment, pulled the latest version of PlantCV and now I am getting the following error when I run my script:

`Traceback (most recent call last):
  File "C:/Path/To/plantcv_pipeline.py", line 140, in <module>
    main()
  File "C:/Path/To/plantcv_pipeline.py", line 110, in main
    roi_objects, hierarchy3, kept_mask, obj_area = pcv.roi_objects(img, 'cutto', roi1, roi_hierarchy, id_objects, obj_hierarchy)
  File "c:\Path\To\Anaconda\envs\plantcv\lib\site-packages\plantcv-3.4.0+40.g2c2dd07-py3.7.egg\plantcv\plantcv\roi_objects.py", line 50, in roi_objects
    if roi_type.upper() == 'PARTIAL' or roi_type.upper() == 'LARGEST':
AttributeError: 'numpy.ndarray' object has no attribute 'upper'`

I have not adjusted my Python script.

Here is my `pip freeze`:

`asn1crypto==0.24.0
atomicwrites==1.3.0
attrs==19.1.0
backcall==0.1.0
bleach==3.1.0
certifi==2019.3.9
cffi==1.12.3
chardet==3.0.4
cloudpickle==1.2.1
colorama==0.4.1
coverage==4.5.3
coveralls==1.8.1
cryptography==2.7
cycler==0.10.0
cytoolz==0.9.0.1
dask==1.2.2
decorator==4.4.0
defusedxml==0.5.0
descartes==1.1.0
docopt==0.6.2
entrypoints==0.3
idna==2.8
imageio==2.5.0
importlib-metadata==0.18
ipykernel==5.1.1
ipython==7.5.0
ipython-genutils==0.2.0
jedi==0.13.3
Jinja2==2.10.1
jsonschema==3.0.1
jupyter-client==5.2.4
jupyter-core==4.4.0
kiwisolver==1.1.0
MarkupSafe==1.1.1
matplotlib==3.1.0
mistune==0.8.4
mizani==0.5.4
more-itertools==4.3.0
nb-conda==2.2.1
nb-conda-kernels==2.2.2
nbconvert==5.5.0
nbformat==4.4.0
networkx==2.3
notebook==5.7.8
numpy==1.16.3
olefile==0.46
opencv-python==3.4.5.20
packaging==19.0
palettable==3.1.1
pandas==0.24.2
pandocfilters==1.4.2
parso==0.4.0
patsy==0.5.1
pickleshare==0.7.5
Pillow==6.0.0
plantcv==3.4.0+40.g2c2dd07
plotnine==0.5.1
pluggy==0.12.0
prometheus-client==0.7.0
prompt-toolkit==2.0.9
py==1.8.0
pycparser==2.19
Pygments==2.4.2
pyOpenSSL==19.0.0
pyparsing==2.4.0
pyrsistent==0.15.2
PySocks==1.7.0
pytest==4.6.3
python-dateutil==2.8.0
pytz==2019.1
PyWavelets==1.0.3
pywinpty==0.5.5
PyYAML==5.1.1
pyzmq==18.0.1
requests==2.22.0
scikit-image==0.14.3
scipy==1.2.1
Send2Trash==1.5.0
six==1.12.0
statsmodels==0.9.0
terminado==0.8.2
testpath==0.4.2
toolz==0.9.0
tornado==6.0.2
traitlets==4.3.2
urllib3==1.24.3
wcwidth==0.1.7
webencodings==0.5.1
win-inet-pton==1.1.0
wincertstore==0.2
zipp==0.5.1`

Absolutely no data is being written out. I am going to see if I can set-up a parallel environment with an older version of PlantCV to get the work done until I can resolve this.

**Comment by HaleySchuhl** [comment]
> ...line 50, in roi_objects if roi_type.upper() == 'PARTIAL' or roi_type.upper() == 'LARGEST': AttributeError: 'numpy.ndarray' object has no attribute 'upper'

We have added a default `roi_type='partial'` to `pcv.roi_objects()` in PlantCV v3.4, which means we had to reorder the input parameters. The current version is ordered `pcv.roi_objects(img, roi_contour, roi_hierarchy, object_contour, obj_hierarchy, roi_type='partial)` but you don't need to reorder if you include parameter names when you call a function. 


> c:\Path\To\Anaconda\envs\plantcv\lib\site-packages\plantcv\plantcv\object_composition.py:49: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
group = np.vstack(contours[i] for i in ids)

We've also been seeing the NumPy 1.16 warning. We plan to either find a replacement for `np.vstack()` or limit the NumPy version in the PlantCV requirements to make sure `pcv.object_composition()` will continue working. 


>c:\Path\To\Anaconda\envs\plantcv\lib\site-packages\plantcv\plantcv\visualize\pseudocolor.py:131: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
plt.show(block=False)

In the PlantCV __init__.py file we have the following to keep matplotlib from failing while running tests in TravisCI: 
```
if "DISPLAY" not in os.environ and "MPLBACKEND" not in os.environ:
    matplotlib.use("Agg")
``` 
Are you running your workflow from the terminal? I haven't been able to replicate this error but it seems to be a warning; are you still able to save out the pseudocolored image that gets created?

**Comment by AdamDimech** [comment]
Hi @HaleySchuhl thanks so much for your help (I am still learning Python, so your patience has really been appreciated). I am running from the Command Prompt on Windows 10. I have amended my code and now are receiving the following error:

`Traceback (most recent call last):
  File "C:/Path/To/plantcv_pipeline.py", line 143, in <module>
    main()
  File "C:/Path/To/plantcv_pipeline.py", line 113, in main
    roi_objects, hierarchy3, mask, obj_area = pcv.roi_objects(img, roi1, roi_hierarchy, id_objects, obj_hierarchy, roi_type='partial')
TypeError: roi_objects() got multiple values for argument 'roi_type'`

Current version of my code is [here](https://gist.github.com/AdamDimech/e54fe95f7face972192fbd76fa83bf9a)

If I change line 113 to `roi_objects, hierarchy3, mask, obj_area = pcv.roi_objects(img, roi1, roi_hierarchy, id_objects, obj_hierarchy, roi_type=partial)`, I get:

`Traceback (most recent call last):
  File "C:/Path/To/plantcv_pipeline.py", line 143, in <module>
    main()
  File "C:/Path/To/plantcv_pipeline.py", line 113, in main
    roi_objects, hierarchy3, mask, obj_area = pcv.roi_objects(img, roi1, roi_hierarchy, id_objects, obj_hierarchy, roi_type=partial)
NameError: name 'partial' is not defined`

I have been checking out the [PlantCV Updating](https://plantcv.readthedocs.io/en/latest/updating/) page and amended my code as best I could to address recent changes.

**Comment by HaleySchuhl** [comment]
@AdamDimech This is strange! The first error seems to suggest it's using an older version of PlantCV where `roi_type` is still the second parameter in `pcv.roi_objects()`, thus finding multiple values for the same argument. Regardless, including parameter names for all inputs ought to resolve this and make the line robust to different versions of PlantCV.
``` 
roi_objects, hierarchy3, mask, obj_area = pcv.roi_objects(img=img, roi_contour=roi1, roi_hierarchy=roi_hierarchy, object_contour=id_objects, obj_hierarchy=obj_hierarchy, roi_type='partial')
```

**Comment by AdamDimech** [comment]
Hi @HaleySchuhl 

Thanks for the code amendment. I am still getting no image output (but am getting data now). I went back to basics and re-did my script in Jupiter Notebook. Here is [my IPYNB code](https://gist.github.com/AdamDimech/ba55255b54854a2a3c83e83e1bcb91b1). You will notice that all steps complete including image output. 

Here is my [Python script](https://gist.github.com/AdamDimech/d354966c03dad5f72f6f014a6f86b39d) based off the same. I still get the Agg Matplotlib warning despite the code that you included in init.py. I manually added a line `mpl.use('Agg')` to my script which also doesn't work.

I feel that I am so close but can't nut out that last step. I use the `-w` flag when running from the command line, I have also tried `pcv.params.debug = "plot"` in my code. A `pip freeze` shows PlantCV is Version 3.4.0.

I also suggest a task:

- [ ] Update [VIS Tutorial](https://plantcv.readthedocs.io/en/latest/vis_tutorial/) with new syntax for `pcv.roi_objects`

**Comment by HaleySchuhl** [comment]
Hi @AdamDimech ,

Would you also provide your shell script? The matplotlib warning message might be inevitable since it seems there is nothing in `os.environ` when running from the command line in Windows. However this warning is letting you know there's no graphical user interface from the command line which fine since we don't expect it to plot to the screen anywhere.

`pcv.params.debug='plot'` indicates you'd like the images plot to the screen but `pcv.params.debug='print'` will save the images to your output directory. This will print all intermediate images, so if you're just interested in those images created by the analysis functions you can just reset the debug mode before those lines in your python script. Alternatively, you could use `pcv.print_image()` even when debug mode is set to `None` for each desired output image if you have specific paths/filenames. Usually we will add a line like `pcv.print_image(img=pseudocolored_img, filename=args.outdir + "/pseudocolored" + filename)` as to avoid images overwriting each other. 

I hadn't realized I forgot to update the `pcv.roi_objects()` syntax in the tutorials; I will have those updates in the next PR.

**Comment by HaleySchuhl** [comment]
Hi @AdamDimech ,

Would you also provide your shell script? The matplotlib warning message might be inevitable since it seems there is nothing in `os.environ` when running from the command line in Windows. However this warning is letting you know there's no graphical user interface from the command line which fine since we don't expect it to plot to the screen anywhere.

`pcv.params.debug='plot'` indicates you'd like the images plot to the screen but `pcv.params.debug='print'` will save the images to your output directory. This will print all intermediate images, so if you're just interested in those images created by the analysis functions you can just reset the debug mode before those lines in your python script. Alternatively, you could use `pcv.print_image()` even when debug mode is set to `None` for each desired output image if you have specific paths/filenames. Usually we will add a line like `pcv.print_image(img=pseudocolored_img, filename=args.outdir + "/pseudocolored" + filename)` as to avoid images overwriting each other. 

I hadn't realized I forgot to update the `pcv.roi_objects()` syntax in the tutorials; I will have those updates in the next PR.

**Comment by AdamDimech** [comment]
Hi @HaleySchuhl 

I don't use a shell script. I run this straight from the command line as follows:

`C:/Path/To/plantcv/plantcv/plantcv-workflow.py -d "G:/Path/To/Files/" -a filename -p C:/Path/To/plantcv_pipeline.py -i G:/Path/To/Files/Output" -j "G:/Path/To/Files/Output/json/results.json" -f id -t JPG -T 16 -w`

Your last code suggestion has resulted in pseudocoloured images being produced (which is excellent!), but I am confused:

This works:
`pseudocolored_img = pcv.visualize.pseudocolor(gray_img=pseudo_grey, obj=None, mask=mask, axes=True, background="black", colorbar=True, cmap='jet')
pcv.print_image(img=pseudocolored_img, filename=args.outdir + "/Pseudocolour-" + filename)`

But this doesn't:
`color_histogram = pcv.analyze_color(img, mask, 'all')
pcv.print_image(img=color_histogram, filename=args.outdir + "/Histogram-" + filename)`

The error reads:

`File "C:/Path/To/plantcv_pipeline.py", line 159, in <module>
    main()
  File "C:/Path/To/plantcv_pipeline.py", line 142, in main
    pcv.print_image(img=color_histogram, filename=args.outdir + "/Histogram-" + filename)
  File "C:\Path\To\Anaconda\envs\plantcv\lib\site-packages\plantcv\plantcv\print_image.py", line 37, in print_image
    fatal_error("Error writing file " + filename + ": " + str(sys.exc_info()[0]))
  File "C:\Path\To\Anaconda\envs\plantcv\lib\site-packages\plantcv\plantcv\fatal_error.py", line 14, in fatal_error
    raise RuntimeError(error)
RuntimeError: Error writing file G:/Path/To/Output/Histogram-123456.JPG: None`

According to [ReadTheDocs](https://plantcv.readthedocs.io/en/latest/print_image/), `pcv.print_image` "can handle matplotlib Figures (like the one returned by pcv.visualize.pseudocolor) and plotnine ggplots (like the histograms returned in pcv.analyze_nir_intensity, pcv.analyze_color, pcv.visualize.histogram, and pcv.fluor_fvfm)."

Also, I am unable to output the shape and boundary images using this method (although I note that `analyze_object` and `analyze_bound_horizontal` aren't mentioned in the help. Is there a solution to this?

Thanks again for your help.

**Comment by HaleySchuhl** [comment]
Hi @AdamDimech ,

I've ran into this same thing with `pcv.analyze_color()` before! I actually just updated the error message for `pcv.print_image()` to be more informative after running into it recently.

PlantCV didn't used to return the image itself but a list of data and the name of the image that would get printed out when `pcv.params.debug='print'` but in the current version we store data to the Outputs class and return the actual image. In the case of `pcv.analyze_object()` it returns a list of the marked up image and a mask, and `pcv.analyze_bound_horizontal()` is basically the same where it returns a list of two images. For `pcv.analyze_color()` it returns a list that contains the histogram due to this legacy stuff. I believe the plan is to get rid of the list and just start returning the actual image objects. For now, you can index the list that gets returned in order to save the image.  

```
color_histogram = pcv.analyze_color(img, mask, 'all') 
pcv.print_image(img=color_histogram[0], filename=args.outdir + "/Histogram-" + filename)
```

I'll be sure to make the documentation more detailed regarding `pcv.print_result()` and in the analysis functions.

**Comment by HaleySchuhl** [comment]
I opened a new issue to address the image returns (#402 ). I plan to have these changes added to a pull request today!

**Comment by AdamDimech** [comment]
Thanks @HaleySchuhl! I am now getting all of the image output that I expect.

**Comment by HaleySchuhl** [comment]
Feel welcome to reopen with any additional questions/suggestions!
